openapi: 3.0.0
info:
  title: Metabolite API
  description: API for metabolite family configuration, evaluation, and recommendations.
  version: 1.0.0
servers:
  - url: "http://localhost:8000/api"
paths:
  /predict:
    post:
      summary: Predicts the best configuration for separating a metabolite family.
      description: Receives a metabolite family and returns an optimal configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The name of the metabolite family.
              required:
                - family
      responses:
        200:
          description: Configuration predicted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  configuration:
                    type: object
                    properties:
                      eluyente1:
                        type: string
                      eluyente2:
                        type: string
                      ph1:
                        type: number
                        format: float
                      ph2:
                        type: number
                        format: float
                      eluyente_1_gradiente:
                        type: array
                        items:
                          type: number
                          format: float
                      eluyente_2_gradiente:
                        type: array
                        items:
                          type: number
                          format: float
                      t_gradiente:
                        type: array
                        items:
                          type: number
                          format: float
                      columna:
                        type: object
                        properties:
                          name:
                            type: string
                          usp_code:
                            type: string
                          length:
                            type: number
                          particle_size:
                            type: number
                          temperature:
                            type: number
                          flowrate:
                            type: number
                          t0:
                            type: number
        400:
          description: Bad request, missing "family" field or incorrect family.
        404:
          description: Metabolite family not found.
          
  /evaluate/alpha:
    post:
      summary: Evaluates the "alpha" score of a configuration for a metabolite family.
      description: Receives a family and a configuration and returns the alpha score.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The name of the metabolite family.
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    t_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: number
                        particle_size:
                          type: number
                        temperature:
                          type: number
                        flowrate:
                          type: number
                        t0:
                          type: number
      responses:
        200:
          description: Alpha score evaluation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  alpha_score:
                    type: number
                    format: float
        400:
          description: Bad request, missing "family" or "configuration".
        404:
          description: Metabolite family not found.
          
  /evaluate/diff:
    post:
      summary: Evaluates the "diff" score of a configuration for a metabolite family.
      description: Receives a family and a configuration and returns the diff score.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The name of the metabolite family.
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    t_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: number
                        particle_size:
                          type: number
                        temperature:
                          type: number
                        flowrate:
                          type: number
                        t0:
                          type: number
      responses:
        200:
          description: Diff score evaluation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  diff_score:
                    type: number
                    format: float
        400:
          description: Bad request, missing "family" or "configuration".
        404:
          description: Metabolite family not found.
          
  /families:
    get:
      summary: Gets a list of metabolite families that we work with.
      responses:
        200:
          description: List of metabolite families retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: No metabolite families found.
          
  /experiments:
    post:
      summary: Adds information about an experiment to the database.
      description: Adds a new experiment to the database with the provided metabolite and column information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name_metabolito:
                  type: string
                formula:
                  type: string
                rt:
                  type: number
                  format: float
                smiles_std:
                  type: string
                inchi_std:
                  type: string
                inchikey_std:
                  type: string
                classyfire:
                  type: object
                  properties:
                    kingdom:
                      type: string
                    superclass:
                      type: string
                    class:
                      type: string
                    subclass:
                      type: string
                    level5:
                      type: string
                    level6:
                      type: string
                comment:
                  type: string
                alternative_parents:
                  type: string
                column:
                  type: object
                  properties:
                    name:
                      type: string
                    usp_code:
                      type: string
                    length:
                      type: number
                    particle_size:
                      type: number
                    temperature:
                      type: number
                    flowrate:
                      type: number
                    t0:
                      type: number
                gradiente:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    t_gradiente:
                      type: array
                      items:
                        type: number
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
      responses:
        200:
          description: Experiment information added successfully.
        400:
          description: Bad request, missing one or more essential fields.
          
  /recommend-family:
    post:
      summary: Recommends the most suitable metabolite family for a given configuration.
      description: Receives a configuration and recommends the most suitable metabolite family.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    t_gradiente:
                      type: array
                      items:
                        type: number
                        format: float
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: number
                        particle_size:
                          type: number
                        temperature:
                          type: number
                        flowrate:
                          type: number
                        t0:
                          type: number
      responses:
        200:
          description: Family recommended successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  family:
                    type: string
        400:
          description: Bad request, missing "configuration" field.
        404:
          description: No suitable family found for the given configuration.
