openapi: 3.0.0
info:
  title: Metabolite Separation API
  version: 1.0.0
  description: API for predicting and evaluating metabolite separation configurations.

paths:
  /predict:
    post:
      summary: Predicts the best configuration to separate a metabolite family.
      description: Given a metabolite family, it returns the best configuration to separate them.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The metabolite family to evaluate.
      responses:
        '200':
          description: Configuration predicted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  configuration:
                    type: object
                    description: The predicted configuration for separating the metabolite family.
        '400':
          description: Bad request, missing or incorrect "family" field.
        '404':
          description: Metabolite family not found.

  /evaluate/alpha:
    post:
      summary: Evaluates the alpha score for a given configuration.
      description: Evaluates how good a configuration is for a metabolite family by calculating the alpha score.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The metabolite family to evaluate.
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                    t_gradiente:
                      type: array
                      items:
                        type: number
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: integer
                        particle_size:
                          type: number
                          format: float
                        temperature:
                          type: number
                          format: float
                        flowrate:
                          type: number
                          format: float
                        t0:
                          type: number
                          format: float
      responses:
        '200':
          description: Alpha evaluation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  relativeScore:
                    type: number
                    description: The relative score compared to other methods.
                  ownMethodScore:
                    type: number
                    description: The score relative to other experiments for the same method.
        '400':
          description: Bad request, missing or incorrect fields.
        '404':
          description: Metabolite family not found.

  /evaluate/diff:
    post:
      summary: Evaluates the diff score for a given configuration.
      description: Evaluates how different a configuration is for a metabolite family by calculating the diff score.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                family:
                  type: string
                  description: The metabolite family to evaluate.
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                    t_gradiente:
                      type: array
                      items:
                        type: number
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: integer
                        particle_size:
                          type: number
                          format: float
                        temperature:
                          type: number
                          format: float
                        flowrate:
                          type: number
                          format: float
                        t0:
                          type: number
                          format: float
      responses:
        '200':
          description: Diff evaluation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  relativeScore:
                    type: number
                    description: The relative score compared to other methods.
                  ownMethodScore:
                    type: number
                    description: The score relative to other experiments for the same method.
        '400':
          description: Bad request, missing or incorrect fields.
        '404':
          description: Metabolite family not found.

  /families:
    get:
      summary: Retrieves a list of metabolite families.
      description: Returns a list of available metabolite families for the system.
      responses:
        '200':
          description: Successfully retrieved metabolite families.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: No metabolite families found.

  /experiments:
    post:
      summary: Adds an experiment to the database.
      description: Adds new experiment data to the system.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name_metabolito:
                  type: string
                  description: The name of the metabolite.
                formula:
                  type: string
                  description: The formula of the metabolite.
                rt:
                  type: number
                  format: float
                  description: Retention time of the metabolite.
                smiles_std:
                  type: string
                  description: The SMILES notation for the metabolite.
                inchi_std:
                  type: string
                  description: The InChI notation for the metabolite.
                inchikey_std:
                  type: string
                  description: The InChI Key for the metabolite.
                classyfire:
                  type: object
                  properties:
                    kingdom:
                      type: string
                    superclass:
                      type: string
                    class:
                      type: string
                    subclass:
                      type: string
                    level5:
                      type: string
                    level6:
                      type: string
                comment:
                  type: string
                  description: Additional comments about the experiment.
                alternative_parents:
                  type: string
                  description: Alternative parent for the metabolite.
                column:
                  type: object
                  properties:
                    name:
                      type: string
                    usp_code:
                      type: string
                    length:
                      type: integer
                    particle_size:
                      type: number
                      format: float
                    temperature:
                      type: number
                      format: float
                    flowrate:
                      type: number
                      format: float
                    t0:
                      type: number
                      format: float
                gradiente:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    t_gradiente:
                      type: array
                      items:
                        type: number
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
      responses:
        '200':
          description: Experiment data added successfully.
        '400':
          description: Bad request, missing or incorrect fields.

  /recommend-family:
    post:
      summary: Recommends the most suitable metabolite family for a given configuration.
      description: Given a configuration, recommends the most appropriate metabolite family.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration:
                  type: object
                  properties:
                    eluyente1:
                      type: string
                    eluyente2:
                      type: string
                    ph1:
                      type: number
                      format: float
                    ph2:
                      type: number
                      format: float
                    eluyente_1_gradiente:
                      type: array
                      items:
                        type: number
                    eluyente_2_gradiente:
                      type: array
                      items:
                        type: number
                    t_gradiente:
                      type: array
                      items:
                        type: number
                    columna:
                      type: object
                      properties:
                        name:
                          type: string
                        usp_code:
                          type: string
                        length:
                          type: integer
                        particle_size:
                          type: number
                          format: float
                        temperature:
                          type: number
                          format: float
                        flowrate:
                          type: number
                          format: float
                        t0:
                          type: number
                          format: float
      responses:
        '200':
          description: Metabolite family recommended successfully.
        '400':
          description: Bad request, missing or incorrect "configuration".
        '404':
          description: No suitable metabolite family found.
