version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Volumen persistente para la base de datos
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  # Scripts de inicialización de MongoDB
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: always

volumes:
  mongodb_data:
    driver: local
#Lo hago solo accesible desde la red local de docker
networks:
  app-network:
    driver: bridge
