version: '3.8'

services:
  api:
    build: .
    environment:
      - PREDICTOR_HOST=predictor
      - PREDICTOR_PORT=8000
      - DATABASE_API_HOST=localhost
      - DATABASE_API_PORT=8010
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    restart: always
