version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: always

  api:
    build:
      context: ./api
    container_name: persistencia-api
    depends_on:
      - mongodb
    ports:
      - "8010:8010"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
