version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - app-network
    restart: always

  metabolite-api:
    image: cmoragon/metabolite-separation-api:latest
    container_name: metabolite-api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"  # puedes cambiarlo si tu app escucha en otro puerto
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=metabolites
    networks:
      - app-network
    restart: always

  predictor:
    image: cmoragon/predictor:latest
    container_name: predictor
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
