version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
    restart: always

  metabolite-api:
    image: cmoragon/metabolite-separation-api:latest
    container_name: metabolite-api
    depends_on:
      - mongodb
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=${MONGO_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    networks:
      - app-network
    restart: always

  predictor:
    image: cmoragon/predictor:latest
    container_name: predictor
    ports:
      - "${PREDICTOR_PORT}:${PREDICTOR_PORT}"
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
